version: "3.7"

services:
  cdnmega:
    container_name: cdnmega.backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: "development"
      NODE_PORT: "9000"
    volumes:
      - ./:/opt/base
      - /opt/base/node_modules
    ports:
      - 9000:9000
      - 9001:9001
    entrypoint: ["npm", "run", "start:dev"]
